generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - project-card/converted
    - project-card/created
    - project-card/deleted
    - project-card/edited
    - project-card/moved
