generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - marketplace-purchase/cancelled
    - marketplace-purchase/changed
    - marketplace-purchase/pending-change
    - marketplace-purchase/pending-change-cancelled
    - marketplace-purchase/purchased
