generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - secret-scanning-alert/created
    - secret-scanning-alert-location/created
    - secret-scanning-alert/reopened
    - secret-scanning-alert/resolved
    - secret-scanning-alert/revoked
