generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - security-advisory/performed
    - security-advisory/published
    - security-advisory/updated
    - security-advisory/withdrawn
    - security-and-analysis
