generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - branch-protection-rule/created
    - branch-protection-rule/deleted
    - branch-protection-rule/edited
