generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - milestone/closed
    - milestone/created
    - milestone/deleted
    - milestone/edited
    - milestone/opened
