generate:
  - types
accessModifier: public
namingStrategy: idiomatic
filter:
  operations:
    - organization/deleted
    - organization/member-added
    - organization/member-invited
    - organization/member-removed
    - organization/renamed
